---
- name: Get public ip address
  command: /usr/bin/curl ifconfig.me
  register: "public_ip"
  sudo: no
  ignore_errors: yes

- name: Message
  debug: msg="Public ip address is {{ public_ip.stdout }}"
  ignore_errors: yes
